email:
  address: 'smtp.gmail.com'
  port: 587,
  domain: 'public.domain.com'
  user_name: '<username>'
  password: '<password>'
  authentication: 'plain'
  enable_starttls_auto: true
  
public_host: 'public.domain.com'